services:
  backend:
    build:
      context: ./backend
      args:
        ENV: production
    container_name: backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/cache:/app/cache
    ports:
      - "${TAILSCALE_IP}:${BACKEND_PORT}:${BACKEND_PORT}"
      - "127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "${TAILSCALE_IP}:443:443"
      - "${TAILSCALE_IP}:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./certs:/etc/ssl/tailscale:ro
