[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "invoice-backend"
version = "0.2.1" # x-release-please-version
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    # Core API & Server
    "fastapi==0.129.0",
    "uvicorn[standard]==0.40.0",
    # Database & Migrations
    "SQLAlchemy==2.0.46",
    "alembic==1.18.4",
    # Data Validation & Settings
    "pydantic-settings==2.13.0",
    "python-multipart==0.0.22",
    # Security & Authentication
    "bcrypt==5.0.0",
    "python-jose==3.5.0",
    "cryptography==46.0.6",
    # Utilities
    "fpdf2==2.8.5",
    "sentry-sdk[fastapi]==2.12.0",
]

[project.optional-dependencies]
dev = [
    "watchfiles==1.1.1",
    "fastapi-cli==0.0.21",
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
seed-db = "app.utilities.seed:main"
