"""initial_schema

Revision ID: 38921fac4ce2
Revises: 
Create Date: 2026-03-29 14:23:37.905147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38921fac4ce2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_invoice_item',
    sa.Column('default_item_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HP', 'KG', 'GT', name='invoicetype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('is_active_global', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('position', sa.Enum('APPEND', 'PREPEND', 'BOTH', name='defaultinvoiceitemposition'), nullable=False),
    sa.PrimaryKeyConstraint('default_item_id')
    )
    op.create_index(op.f('ix_default_invoice_item_default_item_id'), 'default_invoice_item', ['default_item_id'], unique=False)
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('street_number', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('kilometers_to_travel', sa.Float(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patient_label'), 'patient', ['label'], unique=False)
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.create_table('privacy_clause',
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_preamble', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('clause_id')
    )
    op.create_index(op.f('ix_privacy_clause_clause_id'), 'privacy_clause', ['clause_id'], unique=False)
    op.create_table('settings',
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('price_from', sa.Float(), nullable=True),
    sa.Column('price_to', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.create_table('therapy_clause',
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('clause_id')
    )
    op.create_index(op.f('ix_therapy_clause_clause_id'), 'therapy_clause', ['clause_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('kilometers_at_billing', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('HP', 'KG', 'GT', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SAVED', 'PAYMENT_DUE', 'PAID', name='invoicestatus'), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoice_invoice_id'), 'invoice', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_table('invoice_date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_index(op.f('ix_invoice_date_date_id'), 'invoice_date', ['date_id'], unique=False)
    op.create_table('invoice_default_item_association',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('default_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_item_id'], ['default_invoice_item.default_item_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.PrimaryKeyConstraint('invoice_id', 'default_item_id')
    )
    op.create_table('invoice_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['invoice_date.date_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_invoice_item_item_id'), 'invoice_item', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_item_item_id'), table_name='invoice_item')
    op.drop_table('invoice_item')
    op.drop_table('invoice_default_item_association')
    op.drop_index(op.f('ix_invoice_date_date_id'), table_name='invoice_date')
    op.drop_table('invoice_date')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_therapy_clause_clause_id'), table_name='therapy_clause')
    op.drop_table('therapy_clause')
    op.drop_table('settings')
    op.drop_index(op.f('ix_privacy_clause_clause_id'), table_name='privacy_clause')
    op.drop_table('privacy_clause')
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_label'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_default_invoice_item_default_item_id'), table_name='default_invoice_item')
    op.drop_table('default_invoice_item')
    # ### end Alembic commands ###
