"""add is_active_global to default_invoice_item

Revision ID: d0f3f102af99
Revises: bf3be774893d
Create Date: 2026-02-17 16:42:20.227449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = 'd0f3f102af99'
down_revision: Union[str, Sequence[str], None] = 'bf3be774893d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_invoice_item', sa.Column('is_active_global', sa.Boolean(), nullable=False, server_default=expression.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('default_invoice_item', 'is_active_global')
    # ### end Alembic commands ###
